// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPDYm67zAs195KEOjaekLY7S_qiE40uEM',
    appId: '1:247086611179:web:18fccaa89c81343e899cae',
    messagingSenderId: '247086611179',
    projectId: 'bytejournal-32df8',
    authDomain: 'bytejournal-32df8.firebaseapp.com',
    storageBucket: 'bytejournal-32df8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEzLdiK9IPLiVP1SPi-Qoi4nrk4LHHi7A',
    appId: '1:247086611179:android:b456be4994b9c69d899cae',
    messagingSenderId: '247086611179',
    projectId: 'bytejournal-32df8',
    storageBucket: 'bytejournal-32df8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhB7BxdsfNbCev1cBawZL91ZnmLxMlCG8',
    appId: '1:247086611179:ios:4d6efc59106928ab899cae',
    messagingSenderId: '247086611179',
    projectId: 'bytejournal-32df8',
    storageBucket: 'bytejournal-32df8.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhB7BxdsfNbCev1cBawZL91ZnmLxMlCG8',
    appId: '1:247086611179:ios:4d6efc59106928ab899cae',
    messagingSenderId: '247086611179',
    projectId: 'bytejournal-32df8',
    storageBucket: 'bytejournal-32df8.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPDYm67zAs195KEOjaekLY7S_qiE40uEM',
    appId: '1:247086611179:web:4d7ab26ca6716693899cae',
    messagingSenderId: '247086611179',
    projectId: 'bytejournal-32df8',
    authDomain: 'bytejournal-32df8.firebaseapp.com',
    storageBucket: 'bytejournal-32df8.firebasestorage.app',
  );
}
